about/urls.py
from django.conf.urls import url 

from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
]

baca/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^post/(?P<sluginput>[\w-]+)/$',views.detailartikel,name='detail'),
	url(r'^category/(?P<categoryinput>[\w-]+)/$',views.categoryartikel,name='category')
]

edit/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$',views.index, name='index'),
	url(r'^create/',views.create, name='create'),
	url(r'^delete/(?P<delete_id>[0-9]+)$',views.delete,name='delete'),
	url(r'^update/(?P<update_id>[0-9]+)$',views.update,name='update'),
]

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^baca/',include('baca.urls',namespace='baca')),
    url(r'^edit/',include('edit.urls',namespace='edit')),
    url(r'^about/',include('about.urls',namespace='about')),
]

about/models.py
from django.db import models

# Create your models here.

baca/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
from django.core.exceptions import ValidationError

#import file validator
from edit.validatorsn import validate_author
from edit.validatorsn import validate_body

class artikel(models.Model):
	judul = models.CharField(max_length=20)
	penulis = models.CharField(max_length=20,validators = [validate_author])
	list_category = (
		('blog','blog'),
		('berita','berita'),
		('jurnal','jurnal'),
		)
	category = models.CharField(max_length=20,choices=list_category,default='blog')
	body = models.TextField(validators=[validate_body])
	ditulis = models.DateTimeField(auto_now_add=True)
	slug = models.SlugField(blank=True,editable=False)

	def save(self):#agar secara otomatis akan tersimpan,tanpa perlu di isi
		self.slug = slugify(self.judul)# yang akan tersimpan sebagai slug ada judul
		super(artikel, self).save()

	def __str__(self):
		return "{}.{}".format(self.id,self.judul)

edit/models.py
from django.db import models

# Create your models here.

edit/forms.py
from django import forms
from baca.models import artikel

class formartikel(forms.ModelForm):
	class Meta:
		model = artikel
		fields = [
			'penulis',
			'judul',
			'body',
			'category',

		]

about/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	context={
		'judul':'About',
		'heading':'Halama About'
	}
	return render(request,'about/index.html',context)

baca/views.py
from django.shortcuts import render
from .models import artikel
# Create your views here.

def index(request):
	semua_artikel = artikel.objects.all()
	categories = artikel.objects.values('category').distinct()
	context = {
		'judul':'Baca Artikel',
		'heading':'Ayo Baca Artikel ....',
		'semua_artikel':semua_artikel,
		'Categories':categories
	}
	return render (request,'baca/index.html',context)


def detailartikel(request,sluginput):
	semua_artikel  = artikel.objects.get(slug=sluginput)
	context = {
		'judul':'Isi Artikel',
		'heading':'Isi Artikel',
		'semua_artikel':semua_artikel
	}
	return render(request,'baca/detail.html',context)


def categoryartikel(request,categoryinput):
	semua_artikel = artikel.objects.filter(category=categoryinput)
	categories = artikel.objects.values('category').distinct()
	context = {
		'judul':'Category',
		'heading':'Category..',
		'semua_artikel':semua_artikel,
		'Categories':categories
	}
	return render(request,'baca/category.html',context)

edit/views.py
from django.shortcuts import render,redirect
from baca.models import artikel
from .forms import formartikel
# Create your views here.

def index(request):
	semua_artikel = artikel.objects.all()
	context = {
		'penulis'
		'judul':'All Artikel',
		'heading':'All Artikel',
		'semua_artikel':semua_artikel,
	}
	return render(request,'edit/index.html',context)


def create(request):
	form_artikel = formartikel(request.POST or None)

	if request.method =='POST':
		if form_artikel.is_valid():
			form_artikel.save()
		return redirect('edit:index')
	context = {
		'judul':'Create',
		'heading':'Buat Artikel',
		'form_artikel':form_artikel
	}
	return render(request,'edit/create.html',context)

def delete(request,delete_id):
	artikel.objects.filter(id=delete_id).delete()
	return redirect('edit:index')

def update(request,update_id):
	update_artikel = artikel.objects.get(id=update_id)
	data = {
		'judul':update_artikel.judul,
		'body':update_artikel.body,
	}
	form_artikel = formartikel(request.POST or None,initial=data, instance=update_artikel)
	if request.method == 'POST':
		if form_artikel.is_valid():
			form_artikel.save()
		return redirect('edit:index')

	context = {
		'judul':'Update',
		'heading':'Update Artikel',
		'form_artikel':form_artikel
	}
	return render(request,'edit/create.html',context)

website/views.py
from django.shortcuts import render

def index(request):
	context = {
		'judul':'Home | Project',
		'heading':'Selamat Datang di Project CRUD Sederhana'
	}
	return render(request,'index.html',context)

about/templates/about/index.html
{% extends "base.html" %}

{% block judul %}
	{{judul}}
{% endblock judul %}

{% block heading %}
	<h3>{{heading}}</h3>
{% endblock heading %}

{% block content %}
	<div style="text-align: center;">
	<p>Selamat datang di halaman about, Project ini merupakan project CRUD di Django yang saya buat ,semoga kedepan nya saya bisa membuat yang lebih baik dari ini, terima kasih.</p>
</div>
<div style="text-align: right;">
	<p>Salam Penulis</p>
	<p>Bento Sarindo S.M</p>
	<p>Senin,14 Oktober 2019,17.47 WIB</p>
</div>
	<div style="text-align: center;">
		<a class="btn btn-success" href="{% url 'baca:index' %}">Ayo Baca...</a>
		<a class="btn btn-warning" href="{% url 'edit:index' %}">Berkreasi...</a>
		<a class="btn btn-primary" href="{% url 'index' %}">Home</a>
		</div>
{% endblock content %}

baca/templates/baca/category.html
{% extends "base.html" %}

{% block judul %}
	{{judul}}
{% endblock judul %}

{% block heading %}
	<h2>{{heading}}</h2>
{% endblock heading %}

{% block content %}
		<ul class="nav">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'baca:index' %}">Semua Artikel</a>
			</li>
			{% for data in Categories %}
			<li>
				<li class="nav-item">
					<a class="nav-link" href="/baca/category/{{data.category}}">{{data.category}}</a>
				</li>
			</li>
			{% endfor %}
		</ul>
		<br>
		<br>
		{% for post in semua_artikel %}
			<a href="/baca/post/{{post.slug}}">
			<h3>{{post.judul}}</h3>
			</a>
			<p>{{post.penulis}}</p>
			<p>{{post.body|truncatechars:100}}</p>
		{% endfor %}
		<div style="text-align: center;">
		<a class="btn btn-success" href="{% url 'baca:index' %}">Baca Artikel lain...</a>
		<a class="btn btn-warning" href="{% url 'edit:index' %}">Berkreasi...</a>
		<a class="btn btn-primary" href="{% url 'index' %}">Home</a>
		</div>
{% endblock content %}s

baca/templates/baca/detail.html
{% extends "base.html" %}

{% block judul %}
	{{judul}}
{% endblock judul %}

{% block heading %}
	<h4>{{heading}}</h4>
{% endblock heading %}

{% block content %}

		<h5>{{semua_artikel.judul}}</h5>
		<p>{{semua_artikel.penulis}}</p>
		<p>{{semua_artikel.ditulis}} | {{semua_artikel.category}}</p>
		<p>{{semua_artikel.body}}</p>
<a class="btn btn-primary" href="{% url 'index' %}">Home</a>
<a class="btn btn-success" href="{% url 'baca:index' %}">Baca Artikel lain</a>
{% endblock content %}

baca/templates/baca/index.html
{% extends "base.html" %}

{% block judul %}
	{{judul}}
{% endblock judul %}

{% block heading %}
	<h3 style="text-align: center; color: green;">{{heading}}</h3>
{% endblock heading %}

{% block content %}
<ul class="nav">
	<li class="nav-item">
		<a class="nav-link" href="{% url 'baca:index' %}">Semua Artikel</a>
	</li>
	{% for cate in Categories%}
	<li class="nav-item">
		<a class="nav-link" href="/baca/category/{{cate.category}}">{{cate.category}}</a>
	</li>
	{% endfor %}
</ul>
<br>
	{% for artikel in semua_artikel %}
		<a href="/baca/post/{{artikel.slug}}">
		<h4>{{artikel.judul}}</h4>
		</a>
		<p>{{artikel.penulis}}</p>
		<p>{{artikel.body|truncatechars:100}}</p>
		<p>{{artikel.ditulis}} | {{artikel.category}}</p>		
	{% endfor %}
	<a class="btn btn-primary" href="{% url 'index' %}">Home</a>
{% endblock content %}

edit/templates/edit/create.html
{% extends "base.html" %}

{% block judul %}
	{{judul}}
{% endblock judul %}

{% block heading %}
	<h3 style="text-align: center;">{{heading}}</h3>
{% endblock heading%}

{% block content %}
	<form method='POST'>
		{% csrf_token %}
		<table>
			{{form_artikel.as_table}}
		</table>
		<button class="btn btn-info" type="submit">kirim</button>
		<a class="btn btn-secondary" href="{% url 'edit:index' %}">Batal</a>
	</form>

{% endblock content %}

edit/templates/edit/index.html
{% extends "base.html" %}

{% block judul %}
    {{judul}}
{% endblock judul %}

{% block heading %}
   <h3 style="text-align: center;">{{heading}}</h3>
{% endblock heading %}
  <br>
{% block content %}
      <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Judul</th>
          <th scope="col">Isi</th>
          <th scope="col">Category</th>
          <th scope="col">Author</th>
        </tr>
      </thead>
      <tbody>
        {% for post in semua_artikel %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{post.judul}}</td>
          <td>{{post.body|truncatechars:30}}</td>
          <td>{{post.category}}</td>
          <td>{{post.penulis}}</td>
          <td><a class="btn btn-danger" href="{% url 'edit:delete' post.id %}">Hapus</a></td>
          <td><a class="btn btn-warning" href="{% url 'edit:update' post.id %}">Update</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a class="btn btn-primary" href="{% url 'edit:create' %}">Tambah</a>
    <div style="text-align: center;">
    <a class="btn btn-success" href="{% url 'index' %}">Home</a>
<a class="btn btn-info" href="{% url 'baca:index' %}">Baca Artikel</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>
		{% block judul %}
		{% endblock judul %}
	</title>
</head>
<body>
	{% block heading %}
	{% endblock heading %}

	{% block content %}
	{% endblock content %}

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block judul %}
	{{judul}}
{% endblock judul %}

{% block heading %}
	<h2 style="text-align: center; font-family: italic;">{{heading}}</h2><br>
{% endblock heading %}

{% block content %}
	<div style="text-align: center;">
		<a class="btn btn-success" href="{% url 'baca:index' %}">Ayo Baca...</a>
		<a class="btn btn-warning" href="{% url 'edit:index' %}">Berkreasi...</a>
		<a class="btn btn-primary" href="{% url 'about:index' %}">About</a>
	</div>
{% endblock content %}